dist: trusty
sudo: required

language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
#  - osx
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev gcc make

script:
  - cargo build --lib --verbose
  - cargo test --verbose
