[package]
name = "omn-labs"
version = "0.2.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[[bin]]
name = "omn-labs"

[dependencies]
specs = "0.7.0"
time = "*"
rand = "*"
ggez = "0.2.1"

[replace]
"ggez:0.2.1" = { git = 'https://github.com/ggez/ggez', branch = 'gfx' }