[package]
name = "omn-labs"
version = "0.2.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[[bin]]
name = "omn-labs"

[dependencies]
specs = "0.7.0"
time = "*"
rand = "*"
ggez = { git = "https://github.com/ggez/ggez.git", rev = "bc43b714aaf84990aab69301429f03274d084e89" }