[package]
name = "omn-labs"
version = "0.2.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[[bin]]
name = "omn-labs"

[dependencies]
specs = "0.7.0"
time = "*"
rand = "*"
ggez = { git = 'https://github.com/ggez/ggez', rev = 'e66d265' }

[replace]
#"ggez:0.2.1" = { path = '../ggez' }
